version: '3'

services:
  db:
    image: postgres:15.2
    environment:
      POSTGRES_DB: tokenDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  tokens:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATABASE_URL: jdbc:postgresql://db:5432/tokenDB
      SPRING_DATABASE_USERNAME: postgres
      SPRING_DATABASE_PASSWORD: postgres
    depends_on:
      - db

volumes:
 pgdata:
